name: ZMediumToMarkdown
on:
  workflow_dispatch:
  #schedule:
  #  - cron: "15 */6 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.6.5
      - run: gem install ZMediumToMarkdown
      - run: ZMediumToMarkdown -p https://medium.com/pinkoi-engineering/%E5%AF%A6%E6%88%B0%E7%B4%80%E9%8C%84-4-%E5%80%8B%E5%A0%B4%E6%99%AF-7-%E5%80%8B-design-patterns-78507a8de6a5
      - uses: stefanzweifel/git-auto-commit-action@v4
