name: ZMediumToMarkdown
on:
  workflow_dispatch:
  #schedule:
  #  - cron: "15 */6 * * *"

jobs:
  ZMediumToMarkdown:
    runs-on: ubuntu-latest
    steps:
    - name: ZMediumToMarkdown Automatic Bot
      uses: ZhgChgLi/ZMediumToMarkdown@v1.4.7
      with:
        command: '-u zhgchgli'


